_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  WEIGHTS: "./output/fsod/two_branch_training_pascalvoc_split3_pvt_v2_b2_li/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE_AT: 4
    NAME: "build_FCT_backbone"
    TYPE: "pvt_v2_b2_li"
    TRAIN_BRANCH_EMBED: False
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.0
  RPN:
    PRE_NMS_TOPK_TEST: 12000
    POST_NMS_TOPK_TEST: 100
DATASETS:
  TRAIN: ("voc_2007_trainval_all3_10shot",)
  TEST: ("voc_2007_test_all3",)
  TEST_KEEPCLASSES: 'all3'
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00002
  STEPS: (5000, 5000)
  MAX_ITER: 5000
  WARMUP_ITERS: 200
  CHECKPOINT_PERIOD: 5000
INPUT:
  FS:
    FEW_SHOT: True
    SUPPORT_WAY: 5
    SUPPORT_SHOT: 10
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
OUTPUT_DIR: './output/fsod/finetune_dir/two_branch_10shot_finetuning_pascalvoc_split3_pvt_v2_b2_li'
TEST:
  EVAL_PERIOD: 5000
